'------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by coded UI test builder.
'      Version: 10.0.0.0
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace EFL_BasicCodedUITest
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''CheckForCorrectEventOrder - Use 'CheckForCorrectEventOrderExpectedValues' to pass parameters into this method.
        '''</summary>
        Public Sub CheckForCorrectEventOrder()
            Dim uIResultTextBoxEdit As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIResultTextBoxWindow.UIResultTextBoxEdit

            'Verify that 'ResultTextBox' text box's property 'Text' equals 'SelectedValueChanged to 1
            'SelectedValueChanged to 2
            'SelectedValueChanged to 3
            'SelectedValueChanged to 4
            'IsDirtyChanged
            'ValueChanged to 4
            'SelectedValueChanged to 6
            'SelectedValueChanged to 58
            'SelectedValueChanged to 107
            'SelectedValueChanged to 123
            'SelectedValueChanged to 131
            'SelectedValueChanged to 152
            'SelectedValueChanged to 212
            'ValueChanged to 212
            ''
            Assert.AreEqual(Me.CheckForCorrectEventOrderExpectedValues.UIResultTextBoxEditText, uIResultTextBoxEdit.Text)
        End Sub
        
        '''<summary>
        '''CheckFormattedResults - Use 'CheckFormattedResultsExpectedValues' to pass parameters into this method.
        '''</summary>
        Public Sub CheckFormattedResults()
            Dim uIItemEdit As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow12.UIItemEdit
            Dim nullableNumValueInput As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow.NullableNumValueInput
            Dim uIItemEdit1 As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow13.UIItemEdit

            'Verify that 'Unknown Name' text box's property 'Text' equals '41'
            Assert.AreEqual(Me.CheckFormattedResultsExpectedValues.UIItemEditText, uIItemEdit.Text)

            'Verify that 'Unknown Name' text box's property 'Text' equals '56,21249171'
            Assert.AreEqual(Me.CheckFormattedResultsExpectedValues.NullableNumValueInputText, nullableNumValueInput.Text)

            'Verify that 'Unknown Name' text box's property 'Text' equals '01.07.2012'
            Assert.AreEqual(Me.CheckFormattedResultsExpectedValues.UIItemEditText1, uIItemEdit1.Text)
        End Sub
        
        '''<summary>
        '''CheckForNulledCorrectEventOrder - Use 'CheckForNulledCorrectEventOrderExpectedValues' to pass parameters into this method.
        '''</summary>
        Public Sub CheckForNulledCorrectEventOrder()
            Dim uIResultTextBoxEdit As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIResultTextBoxWindow.UIResultTextBoxEdit

            'Verify that 'ResultTextBox' text box's property 'Text' equals 'SelectedValueChanged to 1
            'SelectedValueChanged to 2
            'SelectedValueChanged to 3
            'SelectedValueChanged to 4
            'IsDirtyChanged
            'ValueChanged to 4
            'SelectedValueChanged to 6
            'SelectedValueChanged to 58
            'SelectedValueChanged to 107
            'SelectedValueChanged to 123
            'SelectedValueChanged to 131
            'SelectedValueChanged to 152
            'SelectedValueChanged to 212
            'ValueChanged to 212
            'SelectedValueChanged to * - - - *
            'ValueChanged to * - - - *
            ''
            Assert.AreEqual(Me.CheckForNulledCorrectEventOrderExpectedValues.UIResultTextBoxEditText, uIResultTextBoxEdit.Text)
        End Sub
        
        '''<summary>
        '''EnterFirstCharInNullableRelationPopup - Use 'EnterFirstCharInNullableRelationPopupParams' to pass parameters into this method.
        '''</summary>
        Public Sub EnterFirstCharInNullableRelationPopup()
            Dim nullableRelationalPopup As WinEdit = Me.UIEntityFormsLibTestCoWindow.NullableRelationalPopupContainer.NullableRelationalPopup

            'Type 'l' in 'Unknown Name' text box
            nullableRelationalPopup.Text = Me.EnterFirstCharInNullableRelationPopupParams.NullableRelationalPopupText
        End Sub
        
        '''<summary>
        '''EnterTestDataForNullableDateBox - Use 'EnterTestDataForNullableDateBoxParams' to pass parameters into this method.
        '''</summary>
        Public Sub EnterTestDataForNullableDateBox()
            Dim nullableNumValueInput As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow.NullableNumValueInput
            Dim uIPropsButton As WinButton = Me.UIEntityFormsLibTestCoWindow.UIPropsWindow3.UIPropsButton
            Dim uIItemEdit As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow13.UIItemEdit

            'Type '{Tab}' in 'Unknown Name' text box
            Keyboard.SendKeys(nullableNumValueInput, Me.EnterTestDataForNullableDateBoxParams.NullableNumValueInputSendKeys, ModifierKeys.None)

            'Type '{Tab}' in 'Prop's' button
            Keyboard.SendKeys(uIPropsButton, Me.EnterTestDataForNullableDateBoxParams.UIPropsButtonSendKeys, ModifierKeys.None)

            'Type '1,7,2012' in 'Unknown Name' text box
            uIItemEdit.Text = Me.EnterTestDataForNullableDateBoxParams.UIItemEditText
        End Sub
        
        '''<summary>
        '''EnterTestDataForNullableIntBox - Use 'EnterTestDataForNullableIntBoxParams' to pass parameters into this method.
        '''</summary>
        Public Sub EnterTestDataForNullableIntBox()
            Dim uIItemEdit As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow11.UIItemEdit
            Dim uIPropsButton As WinButton = Me.UIEntityFormsLibTestCoWindow.UIPropsWindow1.UIPropsButton
            Dim uIItemEdit1 As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow12.UIItemEdit

            'Type '{Tab}' in 'Unknown Name' text box
            Keyboard.SendKeys(uIItemEdit, Me.EnterTestDataForNullableIntBoxParams.UIItemEditSendKeys, ModifierKeys.None)

            'Type '{Tab}' in 'Prop's' button
            Keyboard.SendKeys(uIPropsButton, Me.EnterTestDataForNullableIntBoxParams.UIPropsButtonSendKeys, ModifierKeys.None)

            'Type '1+2*3*(6+6)/(10-8)+((12-10)*2)' in 'Unknown Name' text box
            uIItemEdit1.Text = Me.EnterTestDataForNullableIntBoxParams.UIItemEditText
        End Sub
        
        '''<summary>
        '''EnterTestDataForNullableMultilineTextBox - Use 'EnterTestDataForNullableMultilineTextBoxParams' to pass parameters into this method.
        '''</summary>
        Public Sub EnterTestDataForNullableMultilineTextBox()
            Dim uIItemEdit As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow1.UIItemEdit
            Dim uIPropsButton As WinButton = Me.UIEntityFormsLibTestCoWindow.UIPropsWindow.UIPropsButton
            Dim uIItemEdit1 As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow11.UIItemEdit

            'Type '{Tab}' in 'Unknown Name' text box
            Keyboard.SendKeys(uIItemEdit, Me.EnterTestDataForNullableMultilineTextBoxParams.UIItemEditSendKeys, ModifierKeys.None)

            'Type '{Tab}' in 'Prop's' button
            Keyboard.SendKeys(uIPropsButton, Me.EnterTestDataForNullableMultilineTextBoxParams.UIPropsButtonSendKeys, ModifierKeys.None)

            'Type 'In dieser TextBox gibt der Anwender einen noch längeren Text ein, da an dieser Stelle getestet werden soll, wie sich Text verhält, der über mehrere Zeilen bei einer MultiLine-TextBox zu sehen ist.' in 'Unknown Name' text box
            uIItemEdit1.Text = Me.EnterTestDataForNullableMultilineTextBoxParams.UIItemEditText
        End Sub
        
        '''<summary>
        '''EnterTestDataForNullableNumBox - Use 'EnterTestDataForNullableNumBoxParams' to pass parameters into this method.
        '''</summary>
        Public Sub EnterTestDataForNullableNumBox()
            Dim uIItemEdit As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow12.UIItemEdit
            Dim uIPropsButton As WinButton = Me.UIEntityFormsLibTestCoWindow.UIPropsWindow2.UIPropsButton
            Dim nullableNumValueInput As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow.NullableNumValueInput

            'Type '{Tab}' in 'Unknown Name' text box
            Keyboard.SendKeys(uIItemEdit, Me.EnterTestDataForNullableNumBoxParams.UIItemEditSendKeys, ModifierKeys.None)

            'Type '{Tab}' in 'Prop's' button
            Keyboard.SendKeys(uIPropsButton, Me.EnterTestDataForNullableNumBoxParams.UIPropsButtonSendKeys, ModifierKeys.None)

            'Type '1,23+2,33*3,3421*(6,6+6,34)/(10,8-8,8)+((12,5-10,2)*2)' in 'Unknown Name' text box
            nullableNumValueInput.Text = Me.EnterTestDataForNullableNumBoxParams.NullableNumValueInputText
        End Sub
        
        '''<summary>
        '''EnterTestDataForNullableTextBox - Use 'EnterTestDataForNullableTextBoxParams' to pass parameters into this method.
        '''</summary>
        Public Sub EnterTestDataForNullableTextBox()
            Dim uIItemEdit As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow1.UIItemEdit
            Dim uIItemEdit1 As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow2.UIItemEdit

            'Click 'Unknown Name' text box
            Mouse.Click(uIItemEdit, New Point(48, 5))

            'Type 'In dieser TextBox gibt der Anwender einen vergleichsweise langen Namen ein' in 'Unknown Name' text box
            uIItemEdit1.Text = Me.EnterTestDataForNullableTextBoxParams.UIItemEditText
        End Sub
        
        '''<summary>
        '''FinishTestdateInput - Use 'FinishTestdateInputParams' to pass parameters into this method.
        '''</summary>
        Public Sub FinishTestdateInput()
            Dim uIItemEdit As WinEdit = Me.UIEntityFormsLibTestCoWindow.UIItemWindow13.UIItemEdit
            Dim uIPropsButton As WinButton = Me.UIEntityFormsLibTestCoWindow.UIPropsWindow4.UIPropsButton

            'Type '{Tab}' in 'Unknown Name' text box
            Keyboard.SendKeys(uIItemEdit, Me.FinishTestdateInputParams.UIItemEditSendKeys, ModifierKeys.None)

            'Type '{Tab}' in 'Prop's' button
            Keyboard.SendKeys(uIPropsButton, Me.FinishTestdateInputParams.UIPropsButtonSendKeys, ModifierKeys.None)
        End Sub
        
        '''<summary>
        '''LaunchBasicTestForm
        '''</summary>
        Public Sub LaunchBasicTestForm()
            Dim uIShowbasictestUIMenuItem As WinMenuItem = Me.UIEntityFormsLibTestCoWindow.UIMainMenuStripMenuBar.UITestMenuItem.UIShowbasictestUIMenuItem

            'Click 'Test' -> 'Show basic test UI' menu item
            Mouse.Click(uIShowbasictestUIMenuItem, New Point(47, 12))
        End Sub
        
        '''<summary>
        '''NullRelationalPopupInput
        '''</summary>
        Public Sub NullRelationalPopupInput()
            Dim uIMainButtonClient As WinClient = Me.UIEntityFormsLibTestCoWindow.UIMainButtonWindow.UIMainButtonClient
            Dim uIDesktopClient As WinClient = Me.UIItemWindow.UIItemWindow1.UIDesktopClient

            'Click 'mainButton' client
            Mouse.Click(uIMainButtonClient, New Point(5, 7))

            'Click 'Desktop' client
            Mouse.Click(uIDesktopClient, New Point(8, 257))
        End Sub
        
        '''<summary>
        '''PrepareNullableRelationPopup
        '''</summary>
        Public Sub PrepareNullableRelationPopup()
            Dim uISubTest1PopupTestsButton As WinButton = Me.UIEntityFormsLibTestCoWindow.UISubTest1NotdefinedWindow.UISubTest1PopupTestsButton

            'Click 'SubTest 1: Popup Tests' button
            Mouse.Click(uISubTest1PopupTestsButton, New Point(68, 14))
        End Sub
        
        '''<summary>
        '''SelectValuesInRelationalPopup - Use 'SelectValuesInRelationalPopupParams' to pass parameters into this method.
        '''</summary>
        Public Sub SelectValuesInRelationalPopup()
            Dim uIEntityFormsLibTestCoTitleBar As WinTitleBar = Me.UIEntityFormsLibTestCoWindow.UIEntityFormsLibTestCoTitleBar
            Dim nullableRelationalPopup As WinEdit = Me.UIEntityFormsLibTestCoWindow.NullableRelationalPopupContainer.NullableRelationalPopup

            'Click 'EntityFormsLib TestContainer' title bar
            Mouse.Click(uIEntityFormsLibTestCoTitleBar, New Point(286, 8))

            'Type '0004: Picard, Gabby' in 'Unknown Name' text box
            nullableRelationalPopup.Text = Me.SelectValuesInRelationalPopupParams.NullableRelationalPopupText
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property CheckForCorrectEventOrderExpectedValues() As CheckForCorrectEventOrderExpectedValues
            Get
                If (Me.mCheckForCorrectEventOrderExpectedValues Is Nothing) Then
                    Me.mCheckForCorrectEventOrderExpectedValues = New CheckForCorrectEventOrderExpectedValues()
                End If
                Return Me.mCheckForCorrectEventOrderExpectedValues
            End Get
        End Property
        
        Public Overridable ReadOnly Property CheckFormattedResultsExpectedValues() As CheckFormattedResultsExpectedValues
            Get
                If (Me.mCheckFormattedResultsExpectedValues Is Nothing) Then
                    Me.mCheckFormattedResultsExpectedValues = New CheckFormattedResultsExpectedValues()
                End If
                Return Me.mCheckFormattedResultsExpectedValues
            End Get
        End Property
        
        Public Overridable ReadOnly Property CheckForNulledCorrectEventOrderExpectedValues() As CheckForNulledCorrectEventOrderExpectedValues
            Get
                If (Me.mCheckForNulledCorrectEventOrderExpectedValues Is Nothing) Then
                    Me.mCheckForNulledCorrectEventOrderExpectedValues = New CheckForNulledCorrectEventOrderExpectedValues()
                End If
                Return Me.mCheckForNulledCorrectEventOrderExpectedValues
            End Get
        End Property
        
        Public Overridable ReadOnly Property EnterFirstCharInNullableRelationPopupParams() As EnterFirstCharInNullableRelationPopupParams
            Get
                If (Me.mEnterFirstCharInNullableRelationPopupParams Is Nothing) Then
                    Me.mEnterFirstCharInNullableRelationPopupParams = New EnterFirstCharInNullableRelationPopupParams()
                End If
                Return Me.mEnterFirstCharInNullableRelationPopupParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property EnterTestDataForNullableDateBoxParams() As EnterTestDataForNullableDateBoxParams
            Get
                If (Me.mEnterTestDataForNullableDateBoxParams Is Nothing) Then
                    Me.mEnterTestDataForNullableDateBoxParams = New EnterTestDataForNullableDateBoxParams()
                End If
                Return Me.mEnterTestDataForNullableDateBoxParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property EnterTestDataForNullableIntBoxParams() As EnterTestDataForNullableIntBoxParams
            Get
                If (Me.mEnterTestDataForNullableIntBoxParams Is Nothing) Then
                    Me.mEnterTestDataForNullableIntBoxParams = New EnterTestDataForNullableIntBoxParams()
                End If
                Return Me.mEnterTestDataForNullableIntBoxParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property EnterTestDataForNullableMultilineTextBoxParams() As EnterTestDataForNullableMultilineTextBoxParams
            Get
                If (Me.mEnterTestDataForNullableMultilineTextBoxParams Is Nothing) Then
                    Me.mEnterTestDataForNullableMultilineTextBoxParams = New EnterTestDataForNullableMultilineTextBoxParams()
                End If
                Return Me.mEnterTestDataForNullableMultilineTextBoxParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property EnterTestDataForNullableNumBoxParams() As EnterTestDataForNullableNumBoxParams
            Get
                If (Me.mEnterTestDataForNullableNumBoxParams Is Nothing) Then
                    Me.mEnterTestDataForNullableNumBoxParams = New EnterTestDataForNullableNumBoxParams()
                End If
                Return Me.mEnterTestDataForNullableNumBoxParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property EnterTestDataForNullableTextBoxParams() As EnterTestDataForNullableTextBoxParams
            Get
                If (Me.mEnterTestDataForNullableTextBoxParams Is Nothing) Then
                    Me.mEnterTestDataForNullableTextBoxParams = New EnterTestDataForNullableTextBoxParams()
                End If
                Return Me.mEnterTestDataForNullableTextBoxParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property FinishTestdateInputParams() As FinishTestdateInputParams
            Get
                If (Me.mFinishTestdateInputParams Is Nothing) Then
                    Me.mFinishTestdateInputParams = New FinishTestdateInputParams()
                End If
                Return Me.mFinishTestdateInputParams
            End Get
        End Property
        
        Public Overridable ReadOnly Property SelectValuesInRelationalPopupParams() As SelectValuesInRelationalPopupParams
            Get
                If (Me.mSelectValuesInRelationalPopupParams Is Nothing) Then
                    Me.mSelectValuesInRelationalPopupParams = New SelectValuesInRelationalPopupParams()
                End If
                Return Me.mSelectValuesInRelationalPopupParams
            End Get
        End Property
        
        Public ReadOnly Property UIEntityFormsLibTestCoWindow() As UIEntityFormsLibTestCoWindow
            Get
                If (Me.mUIEntityFormsLibTestCoWindow Is Nothing) Then
                    Me.mUIEntityFormsLibTestCoWindow = New UIEntityFormsLibTestCoWindow()
                End If
                Return Me.mUIEntityFormsLibTestCoWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow() As UIItemWindow3
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow3()
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mCheckForCorrectEventOrderExpectedValues As CheckForCorrectEventOrderExpectedValues
        
        Private mCheckFormattedResultsExpectedValues As CheckFormattedResultsExpectedValues
        
        Private mCheckForNulledCorrectEventOrderExpectedValues As CheckForNulledCorrectEventOrderExpectedValues
        
        Private mEnterFirstCharInNullableRelationPopupParams As EnterFirstCharInNullableRelationPopupParams
        
        Private mEnterTestDataForNullableDateBoxParams As EnterTestDataForNullableDateBoxParams
        
        Private mEnterTestDataForNullableIntBoxParams As EnterTestDataForNullableIntBoxParams
        
        Private mEnterTestDataForNullableMultilineTextBoxParams As EnterTestDataForNullableMultilineTextBoxParams
        
        Private mEnterTestDataForNullableNumBoxParams As EnterTestDataForNullableNumBoxParams
        
        Private mEnterTestDataForNullableTextBoxParams As EnterTestDataForNullableTextBoxParams
        
        Private mFinishTestdateInputParams As FinishTestdateInputParams
        
        Private mSelectValuesInRelationalPopupParams As SelectValuesInRelationalPopupParams
        
        Private mUIEntityFormsLibTestCoWindow As UIEntityFormsLibTestCoWindow
        
        Private mUIItemWindow As UIItemWindow3
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'CheckForCorrectEventOrder'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class CheckForCorrectEventOrderExpectedValues

#Region "Fields"
        '''<summary>
        '''Verify that 'ResultTextBox' text box's property 'Text' equals 'SelectedValueChanged to 1
        '''SelectedValueChanged to 2
        '''SelectedValueChanged to 3
        '''SelectedValueChanged to 4
        '''IsDirtyChanged
        '''ValueChanged to 4
        '''SelectedValueChanged to 6
        '''SelectedValueChanged to 58
        '''SelectedValueChanged to 107
        '''SelectedValueChanged to 123
        '''SelectedValueChanged to 131
        '''SelectedValueChanged to 152
        '''SelectedValueChanged to 212
        '''ValueChanged to 212
        '''</summary>
        Public UIResultTextBoxEditText As String = "SelectedValueChanged to 1"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 2"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 3"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "SelectedValueChanged to 4"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"IsDirtyChanged"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ValueChanged to 4"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChang"& _ 
            "ed to 6"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 58"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 107"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueC"& _ 
            "hanged to 123"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 131"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 152"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Selecte"& _ 
            "dValueChanged to 212"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ValueChanged to 212"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'CheckFormattedResults'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class CheckFormattedResultsExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that 'Unknown Name' text box's property 'Text' equals '41'
        '''</summary>
        Public UIItemEditText As String = "41"
        
        '''<summary>
        '''Verify that 'Unknown Name' text box's property 'Text' equals '56,21249171'
        '''</summary>
        Public NullableNumValueInputText As String = "56,21249171"
        
        '''<summary>
        '''Verify that 'Unknown Name' text box's property 'Text' equals '01.07.2012'
        '''</summary>
        Public UIItemEditText1 As String = "01.07.2012"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'CheckForNulledCorrectEventOrder'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class CheckForNulledCorrectEventOrderExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that 'ResultTextBox' text box's property 'Text' equals 'SelectedValueChanged to 1
        '''SelectedValueChanged to 2
        '''SelectedValueChanged to 3
        '''SelectedValueChanged to 4
        '''IsDirtyChanged
        '''ValueChanged to 4
        '''SelectedValueChanged to 6
        '''SelectedValueChanged to 58
        '''SelectedValueChanged to 107
        '''SelectedValueChanged to 123
        '''SelectedValueChanged to 131
        '''SelectedValueChanged to 152
        '''SelectedValueChanged to 212
        '''ValueChanged to 212
        '''SelectedValueChanged to * - - - *
        '''ValueChanged to * - - - *
        ''''
        '''</summary>
        Public UIResultTextBoxEditText As String = "SelectedValueChanged to 1"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 2"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 3"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "SelectedValueChanged to 4"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"IsDirtyChanged"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ValueChanged to 4"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChang"& _ 
            "ed to 6"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 58"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 107"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueC"& _ 
            "hanged to 123"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 131"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to 152"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Selecte"& _ 
            "dValueChanged to 212"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ValueChanged to 212"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SelectedValueChanged to * - - - *"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Va"& _ 
            "lueChanged to * - - - *"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'EnterFirstCharInNullableRelationPopup'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class EnterFirstCharInNullableRelationPopupParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'l' in 'Unknown Name' text box
        '''</summary>
        Public NullableRelationalPopupText As String = "l"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'EnterTestDataForNullableDateBox'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class EnterTestDataForNullableDateBoxParams
        
        #Region "Fields"
        '''<summary>
        '''Type '{Tab}' in 'Unknown Name' text box
        '''</summary>
        Public NullableNumValueInputSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type '{Tab}' in 'Prop's' button
        '''</summary>
        Public UIPropsButtonSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type '1,7,2012' in 'Unknown Name' text box
        '''</summary>
        Public UIItemEditText As String = "1,7,2012"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'EnterTestDataForNullableIntBox'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class EnterTestDataForNullableIntBoxParams
        
        #Region "Fields"
        '''<summary>
        '''Type '{Tab}' in 'Unknown Name' text box
        '''</summary>
        Public UIItemEditSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type '{Tab}' in 'Prop's' button
        '''</summary>
        Public UIPropsButtonSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type '1+2*3*(6+6)/(10-8)+((12-10)*2)' in 'Unknown Name' text box
        '''</summary>
        Public UIItemEditText As String = "1+2*3*(6+6)/(10-8)+((12-10)*2)"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'EnterTestDataForNullableMultilineTextBox'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class EnterTestDataForNullableMultilineTextBoxParams
        
        #Region "Fields"
        '''<summary>
        '''Type '{Tab}' in 'Unknown Name' text box
        '''</summary>
        Public UIItemEditSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type '{Tab}' in 'Prop's' button
        '''</summary>
        Public UIPropsButtonSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type 'In dieser TextBox gibt der Anwender einen noch längeren Text ein, da an dieser Stelle getestet werden soll, wie sich Text verhält, der über mehrere Zeilen bei einer MultiLine-TextBox zu sehen ist.' in 'Unknown Name' text box
        '''</summary>
        Public UIItemEditText As String = "In dieser TextBox gibt der Anwender einen noch längeren Text ein, da an dieser St"& _ 
            "elle getestet werden soll, wie sich Text verhält, der über mehrere Zeilen bei ei"& _ 
            "ner MultiLine-TextBox zu sehen ist."
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'EnterTestDataForNullableNumBox'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class EnterTestDataForNullableNumBoxParams
        
        #Region "Fields"
        '''<summary>
        '''Type '{Tab}' in 'Unknown Name' text box
        '''</summary>
        Public UIItemEditSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type '{Tab}' in 'Prop's' button
        '''</summary>
        Public UIPropsButtonSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type '1,23+2,33*3,3421*(6,6+6,34)/(10,8-8,8)+((12,5-10,2)*2)' in 'Unknown Name' text box
        '''</summary>
        Public NullableNumValueInputText As String = "1,23+2,33*3,3421*(6,6+6,34)/(10,8-8,8)+((12,5-10,2)*2)"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'EnterTestDataForNullableTextBox'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class EnterTestDataForNullableTextBoxParams
        
        #Region "Fields"
        '''<summary>
        '''Type 'In dieser TextBox gibt der Anwender einen vergleichsweise langen Namen ein' in 'Unknown Name' text box
        '''</summary>
        Public UIItemEditText As String = "In dieser TextBox gibt der Anwender einen vergleichsweise langen Namen ein"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'FinishTestdateInput'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class FinishTestdateInputParams
        
        #Region "Fields"
        '''<summary>
        '''Type '{Tab}' in 'Unknown Name' text box
        '''</summary>
        Public UIItemEditSendKeys As String = "{Tab}"
        
        '''<summary>
        '''Type '{Tab}' in 'Prop's' button
        '''</summary>
        Public UIPropsButtonSendKeys As String = "{Tab}"
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'SelectValuesInRelationalPopup'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class SelectValuesInRelationalPopupParams
        
        #Region "Fields"
        '''<summary>
        '''Type '0004: Picard, Gabby' in 'Unknown Name' text box
        '''</summary>
        Public NullableRelationalPopupText As String = "0004: Picard, Gabby"
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIEntityFormsLibTestCoWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "EntityFormsLib TestContainer"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIMainMenuStripMenuBar() As UIMainMenuStripMenuBar
            Get
                If (Me.mUIMainMenuStripMenuBar Is Nothing) Then
                    Me.mUIMainMenuStripMenuBar = New UIMainMenuStripMenuBar(Me)
                End If
                Return Me.mUIMainMenuStripMenuBar
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow() As UIItemWindow
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow(Me)
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow1() As UIItemWindow1
            Get
                If (Me.mUIItemWindow1 Is Nothing) Then
                    Me.mUIItemWindow1 = New UIItemWindow1(Me)
                End If
                Return Me.mUIItemWindow1
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow2() As UIItemWindow2
            Get
                If (Me.mUIItemWindow2 Is Nothing) Then
                    Me.mUIItemWindow2 = New UIItemWindow2(Me)
                End If
                Return Me.mUIItemWindow2
            End Get
        End Property
        
        Public ReadOnly Property UIPropsWindow() As UIPropsWindow
            Get
                If (Me.mUIPropsWindow Is Nothing) Then
                    Me.mUIPropsWindow = New UIPropsWindow(Me)
                End If
                Return Me.mUIPropsWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow11() As UIItemWindow11
            Get
                If (Me.mUIItemWindow11 Is Nothing) Then
                    Me.mUIItemWindow11 = New UIItemWindow11(Me)
                End If
                Return Me.mUIItemWindow11
            End Get
        End Property
        
        Public ReadOnly Property UIPropsWindow1() As UIPropsWindow1
            Get
                If (Me.mUIPropsWindow1 Is Nothing) Then
                    Me.mUIPropsWindow1 = New UIPropsWindow1(Me)
                End If
                Return Me.mUIPropsWindow1
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow12() As UIItemWindow12
            Get
                If (Me.mUIItemWindow12 Is Nothing) Then
                    Me.mUIItemWindow12 = New UIItemWindow12(Me)
                End If
                Return Me.mUIItemWindow12
            End Get
        End Property
        
        Public ReadOnly Property UIPropsWindow2() As UIPropsWindow2
            Get
                If (Me.mUIPropsWindow2 Is Nothing) Then
                    Me.mUIPropsWindow2 = New UIPropsWindow2(Me)
                End If
                Return Me.mUIPropsWindow2
            End Get
        End Property
        
        Public ReadOnly Property UIPropsWindow3() As UIPropsWindow3
            Get
                If (Me.mUIPropsWindow3 Is Nothing) Then
                    Me.mUIPropsWindow3 = New UIPropsWindow3(Me)
                End If
                Return Me.mUIPropsWindow3
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow13() As UIItemWindow13
            Get
                If (Me.mUIItemWindow13 Is Nothing) Then
                    Me.mUIItemWindow13 = New UIItemWindow13(Me)
                End If
                Return Me.mUIItemWindow13
            End Get
        End Property
        
        Public ReadOnly Property UIPropsWindow4() As UIPropsWindow4
            Get
                If (Me.mUIPropsWindow4 Is Nothing) Then
                    Me.mUIPropsWindow4 = New UIPropsWindow4(Me)
                End If
                Return Me.mUIPropsWindow4
            End Get
        End Property
        
        Public ReadOnly Property UISubTest1NotdefinedWindow() As UISubTest1NotdefinedWindow
            Get
                If (Me.mUISubTest1NotdefinedWindow Is Nothing) Then
                    Me.mUISubTest1NotdefinedWindow = New UISubTest1NotdefinedWindow(Me)
                End If
                Return Me.mUISubTest1NotdefinedWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItem9721249171Window() As UIItem9721249171Window
            Get
                If (Me.mUIItem9721249171Window Is Nothing) Then
                    Me.mUIItem9721249171Window = New UIItem9721249171Window(Me)
                End If
                Return Me.mUIItem9721249171Window
            End Get
        End Property
        
        Public ReadOnly Property NullableRelationalPopupContainer() As NullableRelationalPopupContainer
            Get
                If (Me.mNullableRelationalPopupContainer Is Nothing) Then
                    Me.mNullableRelationalPopupContainer = New NullableRelationalPopupContainer(Me)
                End If
                Return Me.mNullableRelationalPopupContainer
            End Get
        End Property
        
        Public ReadOnly Property UIResultTextBoxWindow() As UIResultTextBoxWindow
            Get
                If (Me.mUIResultTextBoxWindow Is Nothing) Then
                    Me.mUIResultTextBoxWindow = New UIResultTextBoxWindow(Me)
                End If
                Return Me.mUIResultTextBoxWindow
            End Get
        End Property
        
        Public ReadOnly Property UIMainButtonWindow() As UIMainButtonWindow
            Get
                If (Me.mUIMainButtonWindow Is Nothing) Then
                    Me.mUIMainButtonWindow = New UIMainButtonWindow(Me)
                End If
                Return Me.mUIMainButtonWindow
            End Get
        End Property
        
        Public ReadOnly Property UIEntityFormsLibTestCoTitleBar() As WinTitleBar
            Get
                If (Me.mUIEntityFormsLibTestCoTitleBar Is Nothing) Then
                    Me.mUIEntityFormsLibTestCoTitleBar = New WinTitleBar(Me)
                    Me.mUIEntityFormsLibTestCoTitleBar.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIEntityFormsLibTestCoTitleBar
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIMainMenuStripMenuBar As UIMainMenuStripMenuBar
        
        Private mUIItemWindow As UIItemWindow
        
        Private mUIItemWindow1 As UIItemWindow1
        
        Private mUIItemWindow2 As UIItemWindow2
        
        Private mUIPropsWindow As UIPropsWindow
        
        Private mUIItemWindow11 As UIItemWindow11
        
        Private mUIPropsWindow1 As UIPropsWindow1
        
        Private mUIItemWindow12 As UIItemWindow12
        
        Private mUIPropsWindow2 As UIPropsWindow2
        
        Private mUIPropsWindow3 As UIPropsWindow3
        
        Private mUIItemWindow13 As UIItemWindow13
        
        Private mUIPropsWindow4 As UIPropsWindow4
        
        Private mUISubTest1NotdefinedWindow As UISubTest1NotdefinedWindow
        
        Private mUIItem9721249171Window As UIItem9721249171Window
        
        Private mNullableRelationalPopupContainer As NullableRelationalPopupContainer
        
        Private mUIResultTextBoxWindow As UIResultTextBoxWindow
        
        Private mUIMainButtonWindow As UIMainButtonWindow
        
        Private mUIEntityFormsLibTestCoTitleBar As WinTitleBar
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIMainMenuStripMenuBar
        Inherits WinMenuBar
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinMenu.PropertyNames.Name) = "MenuStrip1"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UITestMenuItem() As UITestMenuItem
            Get
                If (Me.mUITestMenuItem Is Nothing) Then
                    Me.mUITestMenuItem = New UITestMenuItem(Me)
                End If
                Return Me.mUITestMenuItem
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUITestMenuItem As UITestMenuItem
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UITestMenuItem
        Inherits WinMenuItem
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinMenuItem.PropertyNames.Name) = "Test"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIShowbasictestUIMenuItem() As WinMenuItem
            Get
                If (Me.mUIShowbasictestUIMenuItem Is Nothing) Then
                    Me.mUIShowbasictestUIMenuItem = New WinMenuItem(Me)
                    Me.mUIShowbasictestUIMenuItem.SearchProperties(WinMenuItem.PropertyNames.Name) = "Show basic test UI"
                    Me.mUIShowbasictestUIMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching)
                    Me.mUIShowbasictestUIMenuItem.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIShowbasictestUIMenuItem
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIShowbasictestUIMenuItem As WinMenuItem
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "* - - -*"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains))
            Me.SearchProperties(WinWindow.PropertyNames.Instance) = "3"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property NullableNumValueInput() As WinEdit
            Get
                If (Me.mNullableNumValueInput Is Nothing) Then
                    Me.mNullableNumValueInput = New WinEdit(Me)
                    Me.mNullableNumValueInput.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mNullableNumValueInput
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mNullableNumValueInput As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow1
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "* - - -*"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains))
            Me.SearchProperties(WinWindow.PropertyNames.Instance) = "2"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemEdit() As WinEdit
            Get
                If (Me.mUIItemEdit Is Nothing) Then
                    Me.mUIItemEdit = New WinEdit(Me)
                    Me.mUIItemEdit.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIItemEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow2
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "* - - -*"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains))
            Me.SearchProperties(WinWindow.PropertyNames.Instance) = "2"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemEdit() As WinEdit
            Get
                If (Me.mUIItemEdit Is Nothing) Then
                    Me.mUIItemEdit = New WinEdit(Me)
                    Me.mUIItemEdit.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIItemEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIPropsWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "SetNullableTextValuePropertiesButton"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIPropsButton() As WinButton
            Get
                If (Me.mUIPropsButton Is Nothing) Then
                    Me.mUIPropsButton = New WinButton(Me)
                    Me.mUIPropsButton.SearchProperties(WinButton.PropertyNames.Name) = "Prop's"
                    Me.mUIPropsButton.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIPropsButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIPropsButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow11
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "* - - -*"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemEdit() As WinEdit
            Get
                If (Me.mUIItemEdit Is Nothing) Then
                    Me.mUIItemEdit = New WinEdit(Me)
                    Me.mUIItemEdit.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIItemEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIPropsWindow1
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "SetNullableMultilineTextValuePropertiesButton"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIPropsButton() As WinButton
            Get
                If (Me.mUIPropsButton Is Nothing) Then
                    Me.mUIPropsButton = New WinButton(Me)
                    Me.mUIPropsButton.SearchProperties(WinButton.PropertyNames.Name) = "Prop's"
                    Me.mUIPropsButton.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIPropsButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIPropsButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow12
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "* - - -*"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains))
            Me.SearchProperties(WinWindow.PropertyNames.Instance) = "5"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemEdit() As WinEdit
            Get
                If (Me.mUIItemEdit Is Nothing) Then
                    Me.mUIItemEdit = New WinEdit(Me)
                    Me.mUIItemEdit.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIItemEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIPropsWindow2
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "SetNullableIntValuePropertiesButton"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIPropsButton() As WinButton
            Get
                If (Me.mUIPropsButton Is Nothing) Then
                    Me.mUIPropsButton = New WinButton(Me)
                    Me.mUIPropsButton.SearchProperties(WinButton.PropertyNames.Name) = "Prop's"
                    Me.mUIPropsButton.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIPropsButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIPropsButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIPropsWindow3
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "SetNullableNumValuePropertiesButton"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIPropsButton() As WinButton
            Get
                If (Me.mUIPropsButton Is Nothing) Then
                    Me.mUIPropsButton = New WinButton(Me)
                    Me.mUIPropsButton.SearchProperties(WinButton.PropertyNames.Name) = "Prop's"
                    Me.mUIPropsButton.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIPropsButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIPropsButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow13
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "* - - -*"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains))
            Me.SearchProperties(WinWindow.PropertyNames.Instance) = "4"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemEdit() As WinEdit
            Get
                If (Me.mUIItemEdit Is Nothing) Then
                    Me.mUIItemEdit = New WinEdit(Me)
                    Me.mUIItemEdit.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIItemEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIPropsWindow4
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "SetNullableDateValuePropertiesButton"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIPropsButton() As WinButton
            Get
                If (Me.mUIPropsButton Is Nothing) Then
                    Me.mUIPropsButton = New WinButton(Me)
                    Me.mUIPropsButton.SearchProperties(WinButton.PropertyNames.Name) = "Prop's"
                    Me.mUIPropsButton.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIPropsButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIPropsButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UISubTest1NotdefinedWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "SubTest01Button"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UISubTest1NotdefinedButton() As WinButton
            Get
                If (Me.mUISubTest1NotdefinedButton Is Nothing) Then
                    Me.mUISubTest1NotdefinedButton = New WinButton(Me)
                    Me.mUISubTest1NotdefinedButton.SearchProperties(WinButton.PropertyNames.Name) = "SubTest 1: - Not defined -"
                    Me.mUISubTest1NotdefinedButton.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUISubTest1NotdefinedButton
            End Get
        End Property
        
        Public ReadOnly Property UISubTest1PopupTestsButton() As WinButton
            Get
                If (Me.mUISubTest1PopupTestsButton Is Nothing) Then
                    Me.mUISubTest1PopupTestsButton = New WinButton(Me)
                    Me.mUISubTest1PopupTestsButton.SearchProperties(WinButton.PropertyNames.Name) = "SubTest 1: Popup Tests"
                    Me.mUISubTest1PopupTestsButton.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUISubTest1PopupTestsButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUISubTest1NotdefinedButton As WinButton
        
        Private mUISubTest1PopupTestsButton As WinButton
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItem9721249171Window
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "SingleResult1"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItem9721249171Text() As WinText
            Get
                If (Me.mUIItem9721249171Text Is Nothing) Then
                    Me.mUIItem9721249171Text = New WinText(Me)
                    Me.mUIItem9721249171Text.SearchProperties(WinText.PropertyNames.Name) = "97,21249171"
                    Me.mUIItem9721249171Text.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIItem9721249171Text
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItem9721249171Text As WinText
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class NullableRelationalPopupContainer
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property NullableRelationalPopup() As WinEdit
            Get
                If (Me.mNullableRelationalPopup Is Nothing) Then
                    Me.mNullableRelationalPopup = New WinEdit(Me)
                    Me.mNullableRelationalPopup.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mNullableRelationalPopup
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mNullableRelationalPopup As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIResultTextBoxWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "ResultTextBox"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIResultTextBoxEdit() As WinEdit
            Get
                If (Me.mUIResultTextBoxEdit Is Nothing) Then
                    Me.mUIResultTextBoxEdit = New WinEdit(Me)
                    Me.mUIResultTextBoxEdit.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIResultTextBoxEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIResultTextBoxEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIMainButtonWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "mainButton"
            Me.WindowTitles.Add("EntityFormsLib TestContainer")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIMainButtonClient() As WinClient
            Get
                If (Me.mUIMainButtonClient Is Nothing) Then
                    Me.mUIMainButtonClient = New WinClient(Me)
                    Me.mUIMainButtonClient.WindowTitles.Add("EntityFormsLib TestContainer")
                End If
                Return Me.mUIMainButtonClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIMainButtonClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow3
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.AccessibleName) = "Desktop"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "#32769"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemWindow1() As UIItemWindow14
            Get
                If (Me.mUIItemWindow1 Is Nothing) Then
                    Me.mUIItemWindow1 = New UIItemWindow14(Me)
                End If
                Return Me.mUIItemWindow1
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemWindow1 As UIItemWindow14
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "10.0.40219.1")>  _
    Public Class UIItemWindow14
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIDesktopClient() As WinClient
            Get
                If (Me.mUIDesktopClient Is Nothing) Then
                    Me.mUIDesktopClient = New WinClient(Me)
                End If
                Return Me.mUIDesktopClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIDesktopClient As WinClient
        #End Region
    End Class
End Namespace
